<?php
/**
 * Données des villes pour la Loi Jeanbrun
 *
 * Ce fichier est généré automatiquement par le script Python.
 * NE PAS MODIFIER MANUELLEMENT.
 *
 * Pour mettre à jour les données :
 *   python3 fetch_city_data.py --refresh-data
 *   python3 generate_jeanbrun_pages.py --generate-php-data
 *
 * Généré le : 2026-02-04 20:16:54
 * Nombre de villes : 20
 */

$villes_data = [
    'Paris' => [
        'nom' => 'Paris',
        'code_insee' => '75056',
        'population' => 2103778,
        'departement' => '75 - Paris',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 32.2,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 10518,
        'projets_construction_estimated' => true,
        'code_postal' => '75000',
        'slug' => 'paris',
        'filename' => 'loi-jeanbrun-paris-75000.php',
    ],
    'Marseille' => [
        'nom' => 'Marseille',
        'code_insee' => '13055',
        'population' => 886040,
        'departement' => '13 - Bouches-du-Rhône',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.71,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 4430,
        'projets_construction_estimated' => true,
        'code_postal' => '13000',
        'slug' => 'marseille',
        'filename' => 'loi-jeanbrun-marseille-13000.php',
    ],
    'Lyon' => [
        'nom' => 'Lyon',
        'code_insee' => '69123',
        'population' => 519127,
        'departement' => '69 - Rhône',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 16.05,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 2595,
        'projets_construction_estimated' => true,
        'code_postal' => '69000',
        'slug' => 'lyon',
        'filename' => 'loi-jeanbrun-lyon-69000.php',
    ],
    'Toulouse' => [
        'nom' => 'Toulouse',
        'code_insee' => '31555',
        'population' => 514819,
        'departement' => '31 - Haute-Garonne',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.57,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 2574,
        'projets_construction_estimated' => true,
        'code_postal' => '31000',
        'slug' => 'toulouse',
        'filename' => 'loi-jeanbrun-toulouse-31000.php',
    ],
    'Nice' => [
        'nom' => 'Nice',
        'code_insee' => '06088',
        'population' => 357737,
        'departement' => '06 - Alpes-Maritimes',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 19.5,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1788,
        'projets_construction_estimated' => true,
        'code_postal' => '06000',
        'slug' => 'nice',
        'filename' => 'loi-jeanbrun-nice-06000.php',
    ],
    'Nantes' => [
        'nom' => 'Nantes',
        'code_insee' => '44109',
        'population' => 327734,
        'departement' => '44 - Loire-Atlantique',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.21,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1638,
        'projets_construction_estimated' => true,
        'code_postal' => '44000',
        'slug' => 'nantes',
        'filename' => 'loi-jeanbrun-nantes-44000.php',
    ],
    'Montpellier' => [
        'nom' => 'Montpellier',
        'code_insee' => '34172',
        'population' => 310240,
        'departement' => '34 - Hérault',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.0,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1551,
        'projets_construction_estimated' => true,
        'code_postal' => '34000',
        'slug' => 'montpellier',
        'filename' => 'loi-jeanbrun-montpellier-34000.php',
    ],
    'Strasbourg' => [
        'nom' => 'Strasbourg',
        'code_insee' => '67482',
        'population' => 293771,
        'departement' => '67 - Bas-Rhin',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.01,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1468,
        'projets_construction_estimated' => true,
        'code_postal' => '67000',
        'slug' => 'strasbourg',
        'filename' => 'loi-jeanbrun-strasbourg-67000.php',
    ],
    'Bordeaux' => [
        'nom' => 'Bordeaux',
        'code_insee' => '33063',
        'population' => 267991,
        'departement' => '33 - Gironde',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.66,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1339,
        'projets_construction_estimated' => true,
        'code_postal' => '33000',
        'slug' => 'bordeaux',
        'filename' => 'loi-jeanbrun-bordeaux-33000.php',
    ],
    'Lille' => [
        'nom' => 'Lille',
        'code_insee' => '59350',
        'population' => 238246,
        'departement' => '59 - Nord',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.36,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1191,
        'projets_construction_estimated' => true,
        'code_postal' => '59000',
        'slug' => 'lille',
        'filename' => 'loi-jeanbrun-lille-59000.php',
    ],
    'Rennes' => [
        'nom' => 'Rennes',
        'code_insee' => '35238',
        'population' => 230890,
        'departement' => '35 - Ille-et-Vilaine',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.26,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1154,
        'projets_construction_estimated' => true,
        'code_postal' => '35000',
        'slug' => 'rennes',
        'filename' => 'loi-jeanbrun-rennes-35000.php',
    ],
    'Toulon' => [
        'nom' => 'Toulon',
        'code_insee' => '83137',
        'population' => 179116,
        'departement' => '83 - Var',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.93,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 895,
        'projets_construction_estimated' => true,
        'code_postal' => '83000',
        'slug' => 'toulon',
        'filename' => 'loi-jeanbrun-toulon-83000.php',
    ],
    'Reims' => [
        'nom' => 'Reims',
        'code_insee' => '51454',
        'population' => 177674,
        'departement' => '51 - Marne',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.7,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 888,
        'projets_construction_estimated' => true,
        'code_postal' => '51000',
        'slug' => 'reims',
        'filename' => 'loi-jeanbrun-reims-51000.php',
    ],
    'Saint-Étienne' => [
        'nom' => 'Saint-Étienne',
        'code_insee' => '42218',
        'population' => 173136,
        'departement' => '42 - Loire',
        'zone' => 'B2',
        'plafonds_loyer' => [
            'intermediaire' => 9.5,
            'social' => 7.28,
            'tres_social' => 5.46,
        ],
        'prix_m2_neuf' => 3000,
        'prix_m2_ancien' => 2550,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 9.64,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 9.0,
        'taux_vacance_estimated' => true,
        'projets_construction' => 865,
        'projets_construction_estimated' => true,
        'code_postal' => '42000',
        'slug' => 'saint-etienne',
        'filename' => 'loi-jeanbrun-saint-etienne-42000.php',
    ],
    'Le Havre' => [
        'nom' => 'Le Havre',
        'code_insee' => '76351',
        'population' => 166687,
        'departement' => '76 - Seine-Maritime',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.2,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 833,
        'projets_construction_estimated' => true,
        'code_postal' => '76000',
        'slug' => 'le-havre',
        'filename' => 'loi-jeanbrun-le-havre-76000.php',
    ],
    'Villeurbanne' => [
        'nom' => 'Villeurbanne',
        'code_insee' => '69266',
        'population' => 163684,
        'departement' => '69 - Rhône',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.23,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 818,
        'projets_construction_estimated' => true,
        'code_postal' => '69000',
        'slug' => 'villeurbanne',
        'filename' => 'loi-jeanbrun-villeurbanne-69000.php',
    ],
    'Dijon' => [
        'nom' => 'Dijon',
        'code_insee' => '21231',
        'population' => 161830,
        'departement' => '21 - Côte-d\'Or',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.55,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 809,
        'projets_construction_estimated' => true,
        'code_postal' => '21000',
        'slug' => 'dijon',
        'filename' => 'loi-jeanbrun-dijon-21000.php',
    ],
    'Angers' => [
        'nom' => 'Angers',
        'code_insee' => '49007',
        'population' => 159022,
        'departement' => '49 - Maine-et-Loire',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.07,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 795,
        'projets_construction_estimated' => true,
        'code_postal' => '49000',
        'slug' => 'angers',
        'filename' => 'loi-jeanbrun-angers-49000.php',
    ],
    'Grenoble' => [
        'nom' => 'Grenoble',
        'code_insee' => '38185',
        'population' => 156140,
        'departement' => '38 - Isère',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.27,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 780,
        'projets_construction_estimated' => true,
        'code_postal' => '38000',
        'slug' => 'grenoble',
        'filename' => 'loi-jeanbrun-grenoble-38000.php',
    ],
    'Saint-Denis' => [
        'nom' => 'Saint-Denis',
        'code_insee' => '97411',
        'population' => 155634,
        'departement' => '974 - La Réunion',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.56,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 778,
        'projets_construction_estimated' => true,
        'code_postal' => '97000',
        'slug' => 'saint-denis',
        'filename' => 'loi-jeanbrun-saint-denis-97000.php',
    ],
];

/**
 * Récupère les données d'une ville par son nom
 *
 * @param string $ville Nom de la ville
 * @return array|null Données de la ville ou null si non trouvée
 */
function get_ville_data($ville) {
    global $villes_data;
    return isset($villes_data[$ville]) ? $villes_data[$ville] : null;
}

/**
 * Récupère les données d'une ville par son slug
 *
 * @param string $slug Slug de la ville
 * @return array|null Données de la ville ou null si non trouvée
 */
function get_ville_by_slug($slug) {
    global $villes_data;
    foreach ($villes_data as $ville => $data) {
        if (isset($data['slug']) && $data['slug'] === $slug) {
            return $data;
        }
    }
    return null;
}

/**
 * Récupère toutes les villes triées par population
 *
 * @return array Liste des villes triées
 */
function get_villes_sorted_by_population() {
    global $villes_data;
    $sorted = $villes_data;
    uasort($sorted, function($a, $b) {
        return ($b['population'] ?? 0) - ($a['population'] ?? 0);
    });
    return $sorted;
}

/**
 * Récupère les villes d'une zone spécifique
 *
 * @param string $zone Zone (Abis, A, B1, B2, C)
 * @return array Liste des villes de cette zone
 */
function get_villes_by_zone($zone) {
    global $villes_data;
    return array_filter($villes_data, function($data) use ($zone) {
        return isset($data['zone']) && $data['zone'] === $zone;
    });
}
