<?php
/**
 * Données des villes pour la Loi Jeanbrun
 *
 * Ce fichier est généré automatiquement par le script Python.
 * NE PAS MODIFIER MANUELLEMENT.
 *
 * Pour mettre à jour les données :
 *   python3 fetch_city_data.py --refresh-data
 *   python3 generate_jeanbrun_pages.py --generate-php-data
 *
 * Généré le : 2026-02-04 23:13:39
 * Nombre de villes : 50
 */

$villes_data = [
    'Paris' => [
        'nom' => 'Paris',
        'code_insee' => '75056',
        'population' => 2103778,
        'departement' => '75 - Paris',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 32.2,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 10518,
        'projets_construction_estimated' => true,
        'code_postal' => '75000',
        'slug' => 'paris',
        'filename' => 'loi-jeanbrun-paris-75000.php',
        'intro_text' => 'Capitale française avec ses {{population}} habitants, Paris représente le marché immobilier le plus dynamique en zone {{zone}}.<br><br>La loi Jeanbrun offre ici des opportunités exceptionnelles pour les investisseurs avisés.<br><br>Avec un prix moyen de {{prix_m2_neuf}}€ au m² pour le neuf, le marché parisien bénéficie de plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² qui permettent d\'optimiser la rentabilité tout en profitant d\'un amortissement fiscal généreux.<br><br>La demande locative reste soutenue avec un taux de vacance de seulement {{taux_vacance}}%, garantissant une occupation stable.',
    ],
    'Marseille' => [
        'nom' => 'Marseille',
        'code_insee' => '13055',
        'population' => 886040,
        'departement' => '13 - Bouches-du-Rhône',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.71,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 4430,
        'projets_construction_estimated' => true,
        'code_postal' => '13000',
        'slug' => 'marseille',
        'filename' => 'loi-jeanbrun-marseille-13000.php',
        'intro_text' => 'Deuxième ville de France avec {{population}} habitants, Marseille se positionne comme un marché attractif en zone {{zone}}.<br><br>La loi Jeanbrun y trouve un terrain particulièrement favorable grâce à un prix d\'acquisition abordable de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de cibler une large clientèle tout en bénéficiant d\'un amortissement fiscal avantageux.<br><br>Le dynamisme méditerranéen et les {{projets_construction}} projets de construction prévus confirment l\'attractivité du marché marseillais pour l\'investissement locatif.',
    ],
    'Lyon' => [
        'nom' => 'Lyon',
        'code_insee' => '69123',
        'population' => 519127,
        'departement' => '69 - Rhône',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 16.05,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 2595,
        'projets_construction_estimated' => true,
        'code_postal' => '69000',
        'slug' => 'lyon',
        'filename' => 'loi-jeanbrun-lyon-69000.php',
        'intro_text' => 'Métropole dynamique de {{population}} habitants, Lyon s\'impose comme une valeur sûre en zone {{zone}}.<br><br>La loi Jeanbrun y offre un équilibre optimal entre accessibilité et rentabilité.<br><br>Le prix moyen de {{prix_m2_neuf}}€ au m² pour le neuf permet d\'investir dans une ville en pleine expansion, tandis que les plafonds de loyer à {{plafond_intermediaire}}€/m² assurent des revenus locatifs attractifs.<br><br>La demande locative lyonnaise reste forte, soutenue par un tissu économique robuste et un marché de l\'emploi dynamique.',
    ],
    'Toulouse' => [
        'nom' => 'Toulouse',
        'code_insee' => '31555',
        'population' => 514819,
        'departement' => '31 - Haute-Garonne',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.57,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 2574,
        'projets_construction_estimated' => true,
        'code_postal' => '31000',
        'slug' => 'toulouse',
        'filename' => 'loi-jeanbrun-toulouse-31000.php',
        'intro_text' => 'Ville rose forte de {{population}} habitants, Toulouse combine attractivité économique et qualité de vie en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités remarquables avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>L\'aéronautique et la tech font de Toulouse un marché locatif particulièrement dynamique.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler étudiants et jeunes actifs tout en optimisant le rendement locatif grâce à l\'amortissement fiscal du dispositif.',
    ],
    'Nice' => [
        'nom' => 'Nice',
        'code_insee' => '06088',
        'population' => 357737,
        'departement' => '06 - Alpes-Maritimes',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 19.5,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1788,
        'projets_construction_estimated' => true,
        'code_postal' => '06000',
        'slug' => 'nice',
        'filename' => 'loi-jeanbrun-nice-06000.php',
        'intro_text' => 'Perle de la Côte d\'Azur avec {{population}} habitants, Nice bénéficie du classement en zone {{zone}}.<br><br>La loi Jeanbrun y trouve un marché particulièrement attractif pour l\'investissement locatif.<br><br>Avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf et des plafonds de loyer à {{plafond_intermediaire}}€/m², le marché niçois offre une rentabilité intéressante.<br><br>La demande locative reste soutenue toute l\'année grâce au climat méditerranéen et à l\'attractivité touristique, avec un taux de vacance maîtrisé à {{taux_vacance}}%.',
    ],
    'Nantes' => [
        'nom' => 'Nantes',
        'code_insee' => '44109',
        'population' => 327734,
        'departement' => '44 - Loire-Atlantique',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.21,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1638,
        'projets_construction_estimated' => true,
        'code_postal' => '44000',
        'slug' => 'nantes',
        'filename' => 'loi-jeanbrun-nantes-44000.php',
        'intro_text' => 'Métropole ligérienne de {{population}} habitants, Nantes s\'affirme en zone {{zone}} comme un marché en pleine croissance.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement particulièrement attractives.<br><br>Le prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf permet d\'investir dans une ville dynamique, tandis que les plafonds de loyer à {{plafond_intermediaire}}€/m² assurent des revenus locatifs réguliers.<br><br>Les {{projets_construction}} projets de construction témoignent du dynamisme immobilier nantais et de son potentiel de valorisation.',
    ],
    'Montpellier' => [
        'nom' => 'Montpellier',
        'code_insee' => '34172',
        'population' => 310240,
        'departement' => '34 - Hérault',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.0,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1551,
        'projets_construction_estimated' => true,
        'code_postal' => '34000',
        'slug' => 'montpellier',
        'filename' => 'loi-jeanbrun-montpellier-34000.php',
        'intro_text' => 'Ville méditerranéenne de {{population}} habitants, Montpellier connaît une croissance démographique soutenue en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement remarquables avec un prix moyen de {{prix_m2_neuf}}€ au m² pour le neuf.<br><br>Le marché étudiant particulièrement développé garantit une demande locative pérenne.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler efficacement cette population tout en bénéficiant d\'un amortissement fiscal optimisé sur 9 ans.',
    ],
    'Strasbourg' => [
        'nom' => 'Strasbourg',
        'code_insee' => '67482',
        'population' => 293771,
        'departement' => '67 - Bas-Rhin',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.01,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1468,
        'projets_construction_estimated' => true,
        'code_postal' => '67000',
        'slug' => 'strasbourg',
        'filename' => 'loi-jeanbrun-strasbourg-67000.php',
        'intro_text' => 'Capitale européenne forte de {{population}} habitants, Strasbourg bénéficie d\'un marché locatif dynamique en zone {{zone}}.<br><br>La loi Jeanbrun y trouve un terrain favorable grâce à un prix d\'accès maîtrisé à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Les institutions européennes et le tissu universitaire assurent une demande locative stable.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements de qualité tout en optimisant la rentabilité via l\'amortissement fiscal du dispositif.',
    ],
    'Bordeaux' => [
        'nom' => 'Bordeaux',
        'code_insee' => '33063',
        'population' => 267991,
        'departement' => '33 - Gironde',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.66,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1339,
        'projets_construction_estimated' => true,
        'code_postal' => '33000',
        'slug' => 'bordeaux',
        'filename' => 'loi-jeanbrun-bordeaux-33000.php',
        'intro_text' => 'Métropole bordelaise de {{population}} habitants, Bordeaux s\'impose comme une valeur refuge en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement attractives avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le dynamisme économique porté par l\'aéronautique et le digital garantit une demande locative soutenue.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler jeunes actifs et cadres tout en bénéficiant d\'un amortissement fiscal avantageux.',
    ],
    'Lille' => [
        'nom' => 'Lille',
        'code_insee' => '59350',
        'population' => 238246,
        'departement' => '59 - Nord',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.36,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1191,
        'projets_construction_estimated' => true,
        'code_postal' => '59000',
        'slug' => 'lille',
        'filename' => 'loi-jeanbrun-lille-59000.php',
        'intro_text' => 'Métropole nordiste de {{population}} habitants, Lille bénéficie d\'une position stratégique en zone {{zone}}.<br><br>La loi Jeanbrun y offre des opportunités d\'investissement particulièrement intéressantes avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La proximité de la Belgique et de l\'Angleterre assure un marché locatif dynamique.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements accessibles tout en optimisant le rendement grâce à l\'amortissement fiscal.',
    ],
    'Rennes' => [
        'nom' => 'Rennes',
        'code_insee' => '35238',
        'population' => 230890,
        'departement' => '35 - Ille-et-Vilaine',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.26,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 1154,
        'projets_construction_estimated' => true,
        'code_postal' => '35000',
        'slug' => 'rennes',
        'filename' => 'loi-jeanbrun-rennes-35000.php',
        'intro_text' => 'Capitale bretonne de {{population}} habitants, Rennes connaît une croissance soutenue en zone {{zone}}.<br><br>La loi Jeanbrun y présente des perspectives d\'investissement remarquables avec un prix moyen de {{prix_m2_neuf}}€ au m² pour le neuf.<br><br>Le dynamisme universitaire et technologique garantit une demande locative pérenne.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler étudiants et jeunes actifs tout en bénéficiant d\'un dispositif fiscal avantageux sur 9 ans.',
    ],
    'Toulon' => [
        'nom' => 'Toulon',
        'code_insee' => '83137',
        'population' => 179116,
        'departement' => '83 - Var',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.93,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 895,
        'projets_construction_estimated' => true,
        'code_postal' => '83000',
        'slug' => 'toulon',
        'filename' => 'loi-jeanbrun-toulon-83000.php',
        'intro_text' => 'Ville maritime de {{population}} habitants, Toulon bénéficie du climat méditerranéen en zone {{zone}}.<br><br>La loi Jeanbrun y offre des opportunités d\'investissement attractives avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La base navale et le développement touristique assurent une demande locative stable.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements à des tarifs maîtrisés tout en optimisant la rentabilité via l\'amortissement fiscal.',
    ],
    'Reims' => [
        'nom' => 'Reims',
        'code_insee' => '51454',
        'population' => 177674,
        'departement' => '51 - Marne',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.7,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 888,
        'projets_construction_estimated' => true,
        'code_postal' => '51000',
        'slug' => 'reims',
        'filename' => 'loi-jeanbrun-reims-51000.php',
        'intro_text' => 'Cité des sacres forte de {{population}} habitants, Reims s\'affirme en zone {{zone}} comme un marché en développement.<br><br>La loi Jeanbrun y présente des opportunités intéressantes avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La proximité de Paris et le tissu industriel garantissent une demande locative régulière.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler une large clientèle tout en bénéficiant d\'un amortissement fiscal optimisé.',
    ],
    'Saint-Étienne' => [
        'nom' => 'Saint-Étienne',
        'code_insee' => '42218',
        'population' => 173136,
        'departement' => '42 - Loire',
        'zone' => 'B2',
        'plafonds_loyer' => [
            'intermediaire' => 9.5,
            'social' => 7.28,
            'tres_social' => 5.46,
        ],
        'prix_m2_neuf' => 3000,
        'prix_m2_ancien' => 2550,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 9.64,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 9.0,
        'taux_vacance_estimated' => true,
        'projets_construction' => 865,
        'projets_construction_estimated' => true,
        'code_postal' => '42000',
        'slug' => 'saint-etienne',
        'filename' => 'loi-jeanbrun-saint-etienne-42000.php',
        'intro_text' => 'Ville ligérienne de {{population}} habitants, Saint-Étienne offre un rapport qualité-prix attractif en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement particulièrement accessibles avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La reconversion industrielle et le développement du design assurent un renouveau du marché locatif.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements abordables tout en bénéficiant d\'un dispositif fiscal avantageux.',
    ],
    'Le Havre' => [
        'nom' => 'Le Havre',
        'code_insee' => '76351',
        'population' => 166687,
        'departement' => '76 - Seine-Maritime',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.2,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 833,
        'projets_construction_estimated' => true,
        'code_postal' => '76000',
        'slug' => 'le-havre',
        'filename' => 'loi-jeanbrun-le-havre-76000.php',
        'intro_text' => 'Port normand de {{population}} habitants, Le Havre bénéficie d\'une position stratégique en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement intéressantes avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>L\'activité portuaire et le développement éolien offshore garantissent une demande locative stable.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler employés du port et jeunes actifs tout en optimisant le rendement locatif.',
    ],
    'Villeurbanne' => [
        'nom' => 'Villeurbanne',
        'code_insee' => '69266',
        'population' => 163684,
        'departement' => '69 - Rhône',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.23,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 818,
        'projets_construction_estimated' => true,
        'code_postal' => '69000',
        'slug' => 'villeurbanne',
        'filename' => 'loi-jeanbrun-villeurbanne-69000.php',
        'intro_text' => 'Ville limitrophe de Lyon avec {{population}} habitants, Villeurbanne profite du dynamisme métropolitain en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf, plus accessible que Lyon.<br><br>La proximité immédiate de la Part-Dieu assure une demande locative soutenue.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer une alternative attractive tout en bénéficiant d\'un amortissement fiscal optimisé.',
    ],
    'Dijon' => [
        'nom' => 'Dijon',
        'code_insee' => '21231',
        'population' => 161830,
        'departement' => '21 - Côte-d\'Or',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 15.55,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 809,
        'projets_construction_estimated' => true,
        'code_postal' => '21000',
        'slug' => 'dijon',
        'filename' => 'loi-jeanbrun-dijon-21000.php',
        'intro_text' => 'Capitale bourguignonne de {{population}} habitants, Dijon s\'affirme en zone {{zone}} comme un marché équilibré.<br><br>La loi Jeanbrun y offre des opportunités d\'investissement attractives avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le patrimoine gastronomique et culturel assure une qualité de vie recherchée.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler une clientèle variée tout en bénéficiant d\'un dispositif fiscal avantageux sur 9 ans.',
    ],
    'Angers' => [
        'nom' => 'Angers',
        'code_insee' => '49007',
        'population' => 159022,
        'departement' => '49 - Maine-et-Loire',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 14.07,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 795,
        'projets_construction_estimated' => true,
        'code_postal' => '49000',
        'slug' => 'angers',
        'filename' => 'loi-jeanbrun-angers-49000.php',
        'intro_text' => 'Ville ligérienne de {{population}} habitants, Angers combine douceur de vivre et dynamisme économique en zone {{zone}}.<br><br>La loi Jeanbrun y présente des perspectives d\'investissement remarquables avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le végétal et le numérique font d\'Angers un marché locatif en croissance.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements de qualité tout en optimisant la rentabilité fiscale.',
    ],
    'Grenoble' => [
        'nom' => 'Grenoble',
        'code_insee' => '38185',
        'population' => 156140,
        'departement' => '38 - Isère',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.27,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 780,
        'projets_construction_estimated' => true,
        'code_postal' => '38000',
        'slug' => 'grenoble',
        'filename' => 'loi-jeanbrun-grenoble-38000.php',
        'intro_text' => 'Capitale alpine de {{population}} habitants, Grenoble bénéficie d\'un cadre exceptionnel en zone {{zone}}.<br><br>La loi Jeanbrun y offre des opportunités d\'investissement attractives avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La technologie et la recherche assurent une demande locative qualitative.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler chercheurs et étudiants tout en bénéficiant d\'un amortissement fiscal optimisé sur 9 ans.',
    ],
    'Saint-Denis' => [
        'nom' => 'Saint-Denis',
        'code_insee' => '93066',
        'population' => 149077,
        'departement' => '93 - Seine-Saint-Denis',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 19.89,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 745,
        'projets_construction_estimated' => true,
        'code_postal' => '93000',
        'slug' => 'saint-denis',
        'filename' => 'loi-jeanbrun-saint-denis-93000.php',
        'intro_text' => 'Ville francilienne de {{population}} habitants, Saint-Denis bénéficie de la proximité parisienne en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement particulièrement intéressantes avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf, plus abordable que Paris.<br><br>Le développement urbain et le Grand Paris Express garantissent un potentiel de valorisation important.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer une alternative attractive à la capitale.',
    ],
    'Nîmes' => [
        'nom' => 'Nîmes',
        'code_insee' => '30189',
        'population' => 151839,
        'departement' => '30 - Gard',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.21,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 759,
        'projets_construction_estimated' => true,
        'code_postal' => '30000',
        'slug' => 'nimes',
        'filename' => 'loi-jeanbrun-nimes-30000.php',
        'intro_text' => 'Ville gardoise de {{population}} habitants, Nîmes conjugue patrimoine romain et modernité en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement attractives avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le tourisme culturel et le développement économique assurent une demande locative stable.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements accessibles tout en bénéficiant d\'un amortissement fiscal optimisé sur 9 ans.',
    ],
    'Aix-en-Provence' => [
        'nom' => 'Aix-en-Provence',
        'code_insee' => '13001',
        'population' => 149695,
        'departement' => '13 - Bouches-du-Rhône',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 18.66,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 748,
        'projets_construction_estimated' => true,
        'code_postal' => '13000',
        'slug' => 'aix-en-provence',
        'filename' => 'loi-jeanbrun-aix-en-provence-13000.php',
        'intro_text' => 'Cité provençale de {{population}} habitants, Aix-en-Provence rayonne par son art de vivre en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le dynamisme universitaire et la proximité de Marseille garantissent une demande locative pérenne.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler étudiants et jeunes actifs tout en optimisant la rentabilité fiscale.',
    ],
    'Clermont-Ferrand' => [
        'nom' => 'Clermont-Ferrand',
        'code_insee' => '63113',
        'population' => 146351,
        'departement' => '63 - Puy-de-Dôme',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.99,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 731,
        'projets_construction_estimated' => true,
        'code_postal' => '63000',
        'slug' => 'clermont-ferrand',
        'filename' => 'loi-jeanbrun-clermont-ferrand-63000.php',
        'intro_text' => 'Capitale auvergnate de {{population}} habitants, Clermont-Ferrand s\'affirme comme un pôle économique majeur en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités intéressantes avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>L\'industrie du pneumatique et le tissu universitaire assurent une demande locative régulière.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements de qualité tout en bénéficiant d\'un dispositif fiscal avantageux.',
    ],
    'Le Mans' => [
        'nom' => 'Le Mans',
        'code_insee' => '72181',
        'population' => 146249,
        'departement' => '72 - Sarthe',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.31,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 731,
        'projets_construction_estimated' => true,
        'code_postal' => '72000',
        'slug' => 'le-mans',
        'filename' => 'loi-jeanbrun-le-mans-72000.php',
        'intro_text' => 'Ville sarthoise de {{population}} habitants, Le Mans combine patrimoine historique et innovation en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement attractives avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La renommée internationale des 24 Heures et le développement technologique garantissent une attractivité soutenue.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler une large clientèle tout en optimisant le rendement locatif.',
    ],
    'Brest' => [
        'nom' => 'Brest',
        'code_insee' => '29019',
        'population' => 142346,
        'departement' => '29 - Finistère',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.73,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 711,
        'projets_construction_estimated' => true,
        'code_postal' => '29000',
        'slug' => 'brest',
        'filename' => 'loi-jeanbrun-brest-29000.php',
        'intro_text' => 'Port finistérien de {{population}} habitants, Brest s\'impose comme une métropole maritime dynamique en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités remarquables avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La recherche océanographique et les activités navales assurent une demande locative stable.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements accessibles tout en bénéficiant d\'un amortissement fiscal avantageux sur 9 ans.',
    ],
    'Tours' => [
        'nom' => 'Tours',
        'code_insee' => '37261',
        'population' => 139259,
        'departement' => '37 - Indre-et-Loire',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.1,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 696,
        'projets_construction_estimated' => true,
        'code_postal' => '37000',
        'slug' => 'tours',
        'filename' => 'loi-jeanbrun-tours-37000.php',
        'intro_text' => 'Capitale tourangelle de {{population}} habitants, Tours bénéficie d\'une position stratégique en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement intéressantes avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La douceur de vivre ligérienne et le tissu universitaire garantissent une demande locative pérenne.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler étudiants et jeunes actifs tout en optimisant la rentabilité fiscale.',
    ],
    'Amiens' => [
        'nom' => 'Amiens',
        'code_insee' => '80021',
        'population' => 136449,
        'departement' => '80 - Somme',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.05,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 682,
        'projets_construction_estimated' => true,
        'code_postal' => '80000',
        'slug' => 'amiens',
        'filename' => 'loi-jeanbrun-amiens-80000.php',
        'intro_text' => 'Préfecture picarde de {{population}} habitants, Amiens conjugue patrimoine gothique et renouveau urbain en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement attractives avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La proximité de Paris et le développement économique assurent une demande locative régulière.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements de qualité tout en bénéficiant d\'un dispositif fiscal optimisé.',
    ],
    'Annecy' => [
        'nom' => 'Annecy',
        'code_insee' => '74010',
        'population' => 132117,
        'departement' => '74 - Haute-Savoie',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 18.07,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 660,
        'projets_construction_estimated' => true,
        'code_postal' => '74000',
        'slug' => 'annecy',
        'filename' => 'loi-jeanbrun-annecy-74000.php',
        'intro_text' => 'Perle des Alpes avec {{population}} habitants, Annecy offre un cadre de vie exceptionnel en zone {{zone}}.<br><br>La loi Jeanbrun y présente des perspectives d\'investissement remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le lac et les montagnes garantissent une attractivité touristique et résidentielle permanente.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler une clientèle qualitative tout en optimisant le rendement locatif grâce à l\'amortissement fiscal.',
    ],
    'Limoges' => [
        'nom' => 'Limoges',
        'code_insee' => '87085',
        'population' => 129937,
        'departement' => '87 - Haute-Vienne',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 10.5,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 649,
        'projets_construction_estimated' => true,
        'code_postal' => '87000',
        'slug' => 'limoges',
        'filename' => 'loi-jeanbrun-limoges-87000.php',
        'intro_text' => 'Capitale du Limousin avec {{population}} habitants, Limoges s\'affirme par son savoir-faire en zone {{zone}}.<br><br>La loi Jeanbrun y offre des opportunités d\'investissement accessibles avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Les arts du feu et le développement universitaire assurent une demande locative stable.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements abordables tout en bénéficiant d\'un amortissement fiscal avantageux sur 9 ans.',
    ],
    'Metz' => [
        'nom' => 'Metz',
        'code_insee' => '57463',
        'population' => 122572,
        'departement' => '57 - Moselle',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.6,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 612,
        'projets_construction_estimated' => true,
        'code_postal' => '57000',
        'slug' => 'metz',
        'filename' => 'loi-jeanbrun-metz-57000.php',
        'intro_text' => 'Ville mosellane de {{population}} habitants, Metz conjugue patrimoine médiéval et modernité en zone {{zone}}.<br><br>La loi Jeanbrun y présente des perspectives d\'investissement intéressantes avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La proximité luxembourgeoise et le centre Pompidou assurent une attractivité culturelle et économique.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler une large clientèle tout en optimisant la rentabilité fiscale.',
    ],
    'Perpignan' => [
        'nom' => 'Perpignan',
        'code_insee' => '66136',
        'population' => 121616,
        'departement' => '66 - Pyrénées-Orientales',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.39,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 608,
        'projets_construction_estimated' => true,
        'code_postal' => '66000',
        'slug' => 'perpignan',
        'filename' => 'loi-jeanbrun-perpignan-66000.php',
        'intro_text' => 'Capitale catalane de {{population}} habitants, Perpignan bénéficie du climat méditerranéen en zone {{zone}}.<br><br>La loi Jeanbrun y offre des opportunités d\'investissement attractives avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le soleil et la proximité espagnole garantissent une demande locative régulière.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements accessibles tout en bénéficiant d\'un dispositif fiscal optimisé sur 9 ans.',
    ],
    'Boulogne-Billancourt' => [
        'nom' => 'Boulogne-Billancourt',
        'code_insee' => '92012',
        'population' => 119019,
        'departement' => '92 - Hauts-de-Seine',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 28.9,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 595,
        'projets_construction_estimated' => true,
        'code_postal' => '92000',
        'slug' => 'boulogne-billancourt',
        'filename' => 'loi-jeanbrun-boulogne-billancourt-92000.php',
        'intro_text' => 'Ville francilienne de {{population}} habitants, Boulogne-Billancourt bénéficie d\'une position privilégiée en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf, offrant une alternative à Paris.<br><br>La proximité immédiate de la capitale et le tissu économique dynamique assurent une demande locative soutenue.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler cadres et jeunes actifs tout en optimisant le rendement locatif.',
    ],
    'Besançon' => [
        'nom' => 'Besançon',
        'code_insee' => '25056',
        'population' => 118489,
        'departement' => '25 - Doubs',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.44,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 592,
        'projets_construction_estimated' => true,
        'code_postal' => '25000',
        'slug' => 'besancon',
        'filename' => 'loi-jeanbrun-besancon-25000.php',
        'intro_text' => 'Capitale comtoise de {{population}} habitants, Besançon s\'affirme par son patrimoine horloger en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement intéressantes avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le microtechnique et le tissu universitaire garantissent une demande locative stable.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements de qualité tout en bénéficiant d\'un amortissement fiscal avantageux sur 9 ans.',
    ],
    'Rouen' => [
        'nom' => 'Rouen',
        'code_insee' => '76540',
        'population' => 117662,
        'departement' => '76 - Seine-Maritime',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.77,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 588,
        'projets_construction_estimated' => true,
        'code_postal' => '76000',
        'slug' => 'rouen',
        'filename' => 'loi-jeanbrun-rouen-76000.php',
        'intro_text' => 'Capitale normande de {{population}} habitants, Rouen conjugue patrimoine historique et dynamisme portuaire en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement attractives avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La proximité de Paris et le développement économique assurent une demande locative régulière.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler une large clientèle tout en optimisant la rentabilité fiscale.',
    ],
    'Orléans' => [
        'nom' => 'Orléans',
        'code_insee' => '45234',
        'population' => 116357,
        'departement' => '45 - Loiret',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.53,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 581,
        'projets_construction_estimated' => true,
        'code_postal' => '45000',
        'slug' => 'orleans',
        'filename' => 'loi-jeanbrun-orleans-45000.php',
        'intro_text' => 'Ville ligérienne de {{population}} habitants, Orléans s\'impose par sa position stratégique en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La proximité parisienne et le tissu économique diversifié garantissent une demande locative pérenne.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements accessibles tout en bénéficiant d\'un dispositif fiscal optimisé sur 9 ans.',
    ],
    'Montreuil' => [
        'nom' => 'Montreuil',
        'code_insee' => '93048',
        'population' => 111934,
        'departement' => '93 - Seine-Saint-Denis',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 22.31,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 559,
        'projets_construction_estimated' => true,
        'code_postal' => '93000',
        'slug' => 'montreuil',
        'filename' => 'loi-jeanbrun-montreuil-93000.php',
        'intro_text' => 'Ville limitrophe de Paris avec {{population}} habitants, Montreuil profite du dynamisme métropolitain en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités particulièrement intéressantes avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf, plus accessible que Paris.<br><br>La proximité immédiate de la capitale et le renouveau urbain assurent une demande locative soutenue.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de proposer une alternative attractive tout en optimisant le rendement locatif.',
    ],
    'Caen' => [
        'nom' => 'Caen',
        'code_insee' => '14118',
        'population' => 109400,
        'departement' => '14 - Calvados',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 13.84,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 547,
        'projets_construction_estimated' => true,
        'code_postal' => '14000',
        'slug' => 'caen',
        'filename' => 'loi-jeanbrun-caen-14000.php',
        'intro_text' => 'Capitale normande de {{population}} habitants, Caen combine patrimoine ducal et modernité en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement attractives avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le tissu universitaire et la proximité des plages garantissent une demande locative régulière.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de cibler étudiants et jeunes actifs tout en bénéficiant d\'un amortissement fiscal avantageux sur 9 ans.',
    ],
    'Saint-Paul' => [
        'nom' => 'Saint-Paul',
        'code_insee' => '97415',
        'population' => 108088,
        'departement' => '974 - La Réunion',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 17.75,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 540,
        'projets_construction_estimated' => true,
        'code_postal' => '97000',
        'slug' => 'saint-paul',
        'filename' => 'loi-jeanbrun-saint-paul-97000.php',
        'intro_text' => 'Ville réunionnaise de {{population}} habitants, Saint-Paul bénéficie du climat tropical en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le tourisme et le développement économique insulaire assurent une demande locative stable.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de proposer des logements de qualité tout en optimisant la rentabilité fiscale dans ce département d\'outre-mer.',
    ],
    'Argenteuil' => [
        'nom' => 'Argenteuil',
        'code_insee' => '95018',
        'population' => 106130,
        'departement' => '95 - Val-d\'Oise',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 18.83,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 530,
        'projets_construction_estimated' => true,
        'code_postal' => '95000',
        'slug' => 'argenteuil',
        'filename' => 'loi-jeanbrun-argenteuil-95000.php',
        'intro_text' => 'Ville du Val-d\'Oise avec {{population}} habitants, Argenteuil bénéficie de la proximité parisienne en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement intéressantes avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf, plus abordable que Paris.<br><br>Les liaisons rapides avec la capitale garantissent une demande locative soutenue.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer une alternative attractive tout en bénéficiant d\'un dispositif fiscal optimisé sur 9 ans.',
    ],
    'Mulhouse' => [
        'nom' => 'Mulhouse',
        'code_insee' => '68224',
        'population' => 104978,
        'departement' => '68 - Haut-Rhin',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.35,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 524,
        'projets_construction_estimated' => true,
        'code_postal' => '68000',
        'slug' => 'mulhouse',
        'filename' => 'loi-jeanbrun-mulhouse-68000.php',
        'intro_text' => 'Ville alsacienne de {{population}} habitants, Mulhouse s\'affirme par son industrie et sa culture en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement accessibles avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le tissu industriel et la proximité suisse assurent une demande locative régulière.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements abordables tout en bénéficiant d\'un amortissement fiscal avantageux sur 9 ans.',
    ],
    'Nancy' => [
        'nom' => 'Nancy',
        'code_insee' => '54395',
        'population' => 103671,
        'departement' => '54 - Meurthe-et-Moselle',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.88,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 518,
        'projets_construction_estimated' => true,
        'code_postal' => '54000',
        'slug' => 'nancy',
        'filename' => 'loi-jeanbrun-nancy-54000.php',
        'intro_text' => 'Capitale lorraine de {{population}} habitants, Nancy rayonne par son patrimoine Art Nouveau en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement attractives avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le tissu universitaire et la qualité de vie garantissent une demande locative stable.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler étudiants et jeunes actifs tout en optimisant la rentabilité fiscale.',
    ],
    'Tourcoing' => [
        'nom' => 'Tourcoing',
        'code_insee' => '59599',
        'population' => 98772,
        'departement' => '59 - Nord',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.79,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 493,
        'projets_construction_estimated' => true,
        'code_postal' => '59000',
        'slug' => 'tourcoing',
        'filename' => 'loi-jeanbrun-tourcoing-59000.php',
        'intro_text' => 'Ville nordiste de {{population}} habitants, Tourcoing bénéficie du dynamisme métropolitain lillois en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement particulièrement accessibles avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La proximité de Lille et de la Belgique assurent une demande locative régulière.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements abordables tout en bénéficiant d\'un dispositif fiscal optimisé sur 9 ans.',
    ],
    'Roubaix' => [
        'nom' => 'Roubaix',
        'code_insee' => '59512',
        'population' => 98286,
        'departement' => '59 - Nord',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 12.92,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 491,
        'projets_construction_estimated' => true,
        'code_postal' => '59000',
        'slug' => 'roubaix',
        'filename' => 'loi-jeanbrun-roubaix-59000.php',
        'intro_text' => 'Ville textile de {{population}} habitants, Roubaix connaît un renouveau urbain dynamique en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement attractives avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>La reconversion industrielle et la proximité lilloise garantissent une demande locative en croissance.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements accessibles tout en bénéficiant d\'un amortissement fiscal avantageux sur 9 ans.',
    ],
    'Nanterre' => [
        'nom' => 'Nanterre',
        'code_insee' => '92050',
        'population' => 97783,
        'departement' => '92 - Hauts-de-Seine',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 22.97,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 488,
        'projets_construction_estimated' => true,
        'code_postal' => '92000',
        'slug' => 'nanterre',
        'filename' => 'loi-jeanbrun-nanterre-92000.php',
        'intro_text' => 'Préfecture des Hauts-de-Seine avec {{population}} habitants, Nanterre bénéficie d\'une position stratégique en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf, offrant une alternative à Paris.<br><br>Le quartier d\'affaires de La Défense à proximité assure une demande locative soutenue.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler cadres et employés tout en optimisant le rendement locatif.',
    ],
    'Vitry-sur-Seine' => [
        'nom' => 'Vitry-sur-Seine',
        'code_insee' => '94081',
        'population' => 93963,
        'departement' => '94 - Val-de-Marne',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 20.97,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 469,
        'projets_construction_estimated' => true,
        'code_postal' => '94000',
        'slug' => 'vitry-sur-seine',
        'filename' => 'loi-jeanbrun-vitry-sur-seine-94000.php',
        'intro_text' => 'Ville du Val-de-Marne avec {{population}} habitants, Vitry-sur-Seine profite du dynamisme francilien en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement intéressantes avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf, plus accessible que Paris.<br><br>Les liaisons rapides avec la capitale et le renouveau urbain garantissent une demande locative régulière.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer une alternative attractive tout en bénéficiant d\'un dispositif fiscal optimisé.',
    ],
    'Asnières-sur-Seine' => [
        'nom' => 'Asnières-sur-Seine',
        'code_insee' => '92004',
        'population' => 93941,
        'departement' => '92 - Hauts-de-Seine',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 24.07,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 469,
        'projets_construction_estimated' => true,
        'code_postal' => '92000',
        'slug' => 'asnieres-sur-seine',
        'filename' => 'loi-jeanbrun-asnieres-sur-seine-92000.php',
        'intro_text' => 'Ville des Hauts-de-Seine avec {{population}} habitants, Asnières-sur-Seine bénéficie d\'une localisation privilégiée en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf, offrant une alternative intéressante à Paris.<br><br>La proximité immédiate de la capitale et les excellentes liaisons de transport assurent une demande locative soutenue.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de cibler une large clientèle tout en optimisant le rendement locatif.',
    ],
    'Créteil' => [
        'nom' => 'Créteil',
        'code_insee' => '94028',
        'population' => 93397,
        'departement' => '94 - Val-de-Marne',
        'zone' => 'A',
        'plafonds_loyer' => [
            'intermediaire' => 14.49,
            'social' => 11.11,
            'tres_social' => 8.33,
        ],
        'prix_m2_neuf' => 5500,
        'prix_m2_ancien' => 4675,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 20.26,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 466,
        'projets_construction_estimated' => true,
        'code_postal' => '94000',
        'slug' => 'creteil',
        'filename' => 'loi-jeanbrun-creteil-94000.php',
        'intro_text' => 'Préfecture du Val-de-Marne avec {{population}} habitants, Créteil s\'affirme comme un pôle économique majeur en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement attractives avec un prix d\'accès à {{prix_m2_neuf}}€ au m² dans le neuf, plus abordable que Paris.<br><br>Les centres commerciaux et le tissu économique garantissent une demande locative stable.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de proposer des logements accessibles tout en bénéficiant d\'un amortissement fiscal optimisé sur 9 ans.',
    ],
    'Avignon' => [
        'nom' => 'Avignon',
        'code_insee' => '84007',
        'population' => 92188,
        'departement' => '84 - Vaucluse',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.84,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 460,
        'projets_construction_estimated' => true,
        'code_postal' => '84000',
        'slug' => 'avignon',
        'filename' => 'loi-jeanbrun-avignon-84000.php',
        'intro_text' => 'Cité des Papes avec {{population}} habitants, Avignon rayonne par son patrimoine culturel en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement intéressantes avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le festival international et le tourisme assurent une attractivité permanente.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de cibler une clientèle variée tout en bénéficiant d\'un dispositif fiscal avantageux sur 9 ans.',
    ],
    'Colombes' => [
        'nom' => 'Colombes',
        'code_insee' => '92025',
        'population' => 91053,
        'departement' => '92 - Hauts-de-Seine',
        'zone' => 'Abis',
        'plafonds_loyer' => [
            'intermediaire' => 18.25,
            'social' => 14.0,
            'tres_social' => 10.5,
        ],
        'prix_m2_neuf' => 10000,
        'prix_m2_ancien' => 8500,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 22.87,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 6.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 455,
        'projets_construction_estimated' => true,
        'code_postal' => '92000',
        'slug' => 'colombes',
        'filename' => 'loi-jeanbrun-colombes-92000.php',
        'intro_text' => 'Ville des Hauts-de-Seine avec {{population}} habitants, Colombes profite du dynamisme métropolitain en zone {{zone}}.<br><br>La loi Jeanbrun y offre des perspectives d\'investissement remarquables avec un prix de {{prix_m2_neuf}}€ au m² dans le neuf, plus accessible que Paris.<br><br>Les liaisons rapides avec la capitale et le cadre de vie agréable garantissent une demande locative soutenue.<br><br>Les plafonds de loyer intermédiaire à {{plafond_intermediaire}}€/m² permettent de proposer une alternative attractive tout en optimisant le rendement locatif.',
    ],
    'Poitiers' => [
        'nom' => 'Poitiers',
        'code_insee' => '86194',
        'population' => 89916,
        'departement' => '86 - Vienne',
        'zone' => 'B1',
        'plafonds_loyer' => [
            'intermediaire' => 10.93,
            'social' => 8.38,
            'tres_social' => 6.29,
        ],
        'prix_m2_neuf' => 4000,
        'prix_m2_ancien' => 3400,
        'dvf_transactions_count' => 0,
        'loyer_marche_m2' => 11.94,
        'prix_m2_neuf_estimated' => true,
        'prix_m2_ancien_estimated' => true,
        'taux_vacance' => 7.5,
        'taux_vacance_estimated' => true,
        'projets_construction' => 449,
        'projets_construction_estimated' => true,
        'code_postal' => '86000',
        'slug' => 'poitiers',
        'filename' => 'loi-jeanbrun-poitiers-86000.php',
        'intro_text' => 'Capitale poitevine de {{population}} habitants, Poitiers conjugue patrimoine historique et innovation en zone {{zone}}.<br><br>La loi Jeanbrun y présente des opportunités d\'investissement attractives avec un prix moyen de {{prix_m2_neuf}}€ au m² dans le neuf.<br><br>Le tissu universitaire et le Futuroscope assurent une demande locative pérenne.<br><br>Les plafonds de loyer à {{plafond_intermediaire}}€/m² permettent de cibler étudiants et jeunes actifs tout en bénéficiant d\'un amortissement fiscal avantageux sur 9 ans.',
    ],
];

/**
 * Récupère les données d'une ville par son nom
 *
 * @param string $ville Nom de la ville
 * @return array|null Données de la ville ou null si non trouvée
 */
function get_ville_data($ville) {
    global $villes_data;
    return isset($villes_data[$ville]) ? $villes_data[$ville] : null;
}

/**
 * Récupère les données d'une ville par son slug
 *
 * @param string $slug Slug de la ville
 * @return array|null Données de la ville ou null si non trouvée
 */
function get_ville_by_slug($slug) {
    global $villes_data;
    foreach ($villes_data as $ville => $data) {
        if (isset($data['slug']) && $data['slug'] === $slug) {
            return $data;
        }
    }
    return null;
}

/**
 * Récupère toutes les villes triées par population
 *
 * @return array Liste des villes triées
 */
function get_villes_sorted_by_population() {
    global $villes_data;
    $sorted = $villes_data;
    uasort($sorted, function($a, $b) {
        return ($b['population'] ?? 0) - ($a['population'] ?? 0);
    });
    return $sorted;
}

/**
 * Récupère les villes d'une zone spécifique
 *
 * @param string $zone Zone (Abis, A, B1, B2, C)
 * @return array Liste des villes de cette zone
 */
function get_villes_by_zone($zone) {
    global $villes_data;
    return array_filter($villes_data, function($data) use ($zone) {
        return isset($data['zone']) && $data['zone'] === $zone;
    });
}
